LOGGING:
  LOG_FILE: video_insight.log
  LOG_LEVEL: DEBUG
  CONSOLE_OUTPUT: true
  CLEAR_OLD_LOGS: true

VIDEO_PROCESSING:
  TARGET_FRAME_COUNT: 10
  MIN_SCENE_DURATION: 4
  VISUAL_RECALL_NUM: 5
  AUDIO_RECALL_NUM: 5

ASR_MODEL:
  DEVICE: cuda
  MODEL_ID: openai/whisper-large-v3

TEXT_EMBEDDING_MODEL:
  DEVICE: cpu
  MODEL_ID: BAAI/bge-m3

IMAGE_TEXT_RETRIEVAL_MODEL:
  DEVICE: cpu
  MODEL_ID: BAAI/AltCLIP

RERANKER_MODEL:
  DEVICE: cpu
  MODEL_ID: BAAI/bge-reranker-v2-m3
  